temp_file = open("temp.txt","w")
print("first line",file=temp_file)
print("second line",file=temp_file)
print("third line",file=temp_file)
print("fourth line",file=temp_file)
temp_file.close()
print('===')
temp_file = open('temp.txt','r')
for line in temp_file:
    line = line.strip()
    print(line)
temp_file.close()
print('===')
temp_file = open('temp.txt','r')
my_str =temp_file.read()
print(my_str)
temp_file.close()
print("===")
temp_file = open('temp.txt','r')
lines = temp_file.readlines()
#print(lines)
for line in lines:
    line = line.strip()
    print(line)
temp_file.close()
print('===')
word_list = ['first', 'second', 'third', 'fourth']
out_file = open('outfile.txt', 'w')
out_file.writelines(word_list)
temp_file.close()

